# Generated by Django 3.2.8 on 2021-11-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211104_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_captain',
        ),
    ]
