# Generated by Django 3.2.8 on 2021-11-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remove_player_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
