# Generated by Django 3.2.8 on 2021-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_remove_player_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='file',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
