# Generated by Django 3.2.8 on 2021-11-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_player_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='file',
            field=models.TextField(),
        ),
    ]
