# Generated by Django 3.2.8 on 2021-12-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_alter_player_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='at_bats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='batting_average',
            field=models.DecimalField(decimal_places=3, default=0.333, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='hits',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='homeruns',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='minibat_games_played',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
