# Generated by Django 3.2.8 on 2021-12-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_auto_20211203_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batting_average',
            field=models.IntegerField(),
        ),
    ]
