# Generated by Django 3.2.8 on 2021-12-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_alter_player_batting_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
    ]
