# Generated by Django 3.2.8 on 2021-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('championships', models.IntegerField()),
            ],
        ),
    ]
