# Generated by Django 3.2.8 on 2021-11-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.IntegerField(),
        ),
    ]
