# Generated by Django 3.2.8 on 2021-11-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='file',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
