# Generated by Django 3.2.8 on 2021-12-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='batting_average',
            field=models.DecimalField(decimal_places=3, default=0.33, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='homeruns',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='runs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='runs_against',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
