# Generated by Django 3.2.8 on 2021-12-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20211203_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='batting_average',
            field=models.IntegerField(),
        ),
    ]
