# Generated by Django 3.2.8 on 2021-11-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('teams', models.CharField(max_length=500)),
                ('champions', models.CharField(max_length=25)),
                ('players', models.CharField(max_length=500)),
                ('mvp', models.CharField(max_length=25)),
            ],
        ),
    ]
