# Generated by Django 3.2.8 on 2021-12-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_tourney_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='players',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
