# Generated by Django 3.2.8 on 2021-12-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tourney_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourney',
            name='players',
        ),
    ]
