# Generated by Django 3.2.8 on 2021-12-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20211204_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
