# Generated by Django 3.2.8 on 2021-12-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
