# Generated by Django 3.2.8 on 2021-12-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
    ]
